2025-05-18 00:12:32.121 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration wiim which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-05-18 00:12:32.739 WARNING (MainThread) [aiohttp_fast_zlib] zlib_ng and isal are not available, falling back to zlib, performance will be degraded.
2025-05-18 00:12:32.835 ERROR (MainThread) [haffmpeg.core] FFmpeg fails [Errno 2] No such file or directory: 'ffmpeg'
Traceback (most recent call last):
  File "/ha-venv/lib/python3.13/site-packages/haffmpeg/core.py", line 130, in open
    self._proc = await asyncio.create_subprocess_exec(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/asyncio/subprocess.py", line 224, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        stderr=stderr, **kwds)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 1788, in subprocess_exec
    transport = await self._make_subprocess_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        protocol, popen_args, False, stdin, stdout, stderr,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        bufsize, **kwargs)
        ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/unix_events.py", line 213, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
                                    stdin, stdout, stderr, bufsize,
                                    waiter=waiter, extra=extra,
                                    **kwargs)
  File "/usr/local/lib/python3.13/asyncio/base_subprocess.py", line 39, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                stderr=stderr, bufsize=bufsize, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/unix_events.py", line 855, in _start
    self._proc = subprocess.Popen(
                 ~~~~~~~~~~~~~~~~^
        args, shell=shell, stdin=stdin, stdout=stdout, stderr=stderr,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        universal_newlines=False, bufsize=bufsize, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/subprocess.py", line 1039, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        pass_fds, cwd, env,
                        ^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
                        gid, gids, uid, umask,
                        ^^^^^^^^^^^^^^^^^^^^^^
                        start_new_session, process_group)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/subprocess.py", line 1969, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
2025-05-18 00:12:32.838 WARNING (MainThread) [haffmpeg.tools] Error starting FFmpeg.
2025-05-18 00:12:33.156 ERROR (ImportExecutor_0) [homeassistant.components.camera.img_util] Error loading libturbojpeg; Camera snapshot performance will be sub-optimal
Traceback (most recent call last):
  File "/ha-venv/lib/python3.13/site-packages/homeassistant/components/camera/img_util.py", line 93, in __init__
    TurboJPEGSingleton.__instance = TurboJPEG()
                                    ~~~~~~~~~^^
  File "/ha-venv/lib/python3.13/site-packages/turbojpeg.py", line 300, in __init__
    self.__find_turbojpeg() if lib_path is None else lib_path)
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/ha-venv/lib/python3.13/site-packages/turbojpeg.py", line 967, in __find_turbojpeg
    raise RuntimeError(
    ...<2 lines>...
        'e.g. jpeg = TurboJPEG(lib_path)')
RuntimeError: Unable to locate turbojpeg library automatically. You may specify the turbojpeg library path manually.
e.g. jpeg = TurboJPEG(lib_path)
2025-05-18 00:12:33.392 WARNING (MainThread) [asyncio] Executing <Task pending name='Task-1' coro=<setup_and_run_hass() running at /ha-venv/lib/python3.13/site-packages/homeassistant/runner.py:122> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.13/asyncio/tasks.py:765> cb=[_run_until_complete_cb() at /usr/local/lib/python3.13/asyncio/base_events.py:181] created at /usr/local/lib/python3.13/asyncio/tasks.py:748> took 0.181 seconds
2025-05-18 00:12:33.454 DEBUG (MainThread) [custom_components.wiim.api] WiiM HTTP GET https://192.168.1.68:443/httpapi.asp?command=getPlayerStatusEx (verify_ssl=True)
2025-05-18 00:12:33.456 DEBUG (MainThread) [custom_components.wiim.api] WiiM HTTP GET https://192.168.1.68:443/httpapi.asp?command=getStatusEx (verify_ssl=True)
2025-05-18 00:12:33.457 DEBUG (MainThread) [custom_components.wiim.api] WiiM HTTP GET https://192.168.1.68:443/httpapi.asp?command=multiroom:getSlaveList (verify_ssl=True)
2025-05-18 00:12:33.459 DEBUG (MainThread) [custom_components.wiim.api] WiiM HTTP GET https://192.168.1.116:443/httpapi.asp?command=getPlayerStatusEx (verify_ssl=True)
2025-05-18 00:12:33.460 DEBUG (MainThread) [custom_components.wiim.api] WiiM HTTP GET https://192.168.1.116:443/httpapi.asp?command=getStatusEx (verify_ssl=True)
2025-05-18 00:12:33.461 DEBUG (MainThread) [custom_components.wiim.api] WiiM HTTP GET https://192.168.1.116:443/httpapi.asp?command=multiroom:getSlaveList (verify_ssl=True)
2025-05-18 00:12:33.470 ERROR (MainThread) [homeassistant.components.go2rtc] Could not find go2rtc docker binary
2025-05-18 00:12:33.470 ERROR (MainThread) [homeassistant.setup] Setup failed for 'go2rtc': Integration failed to initialize.
2025-05-18 00:12:33.525 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of 'default_config'. Setup failed for dependencies: ['go2rtc']
2025-05-18 00:12:33.525 ERROR (MainThread) [homeassistant.setup] Setup failed for 'default_config': Could not setup dependencies: go2rtc
2025-05-18 00:12:33.574 DEBUG (MainThread) [custom_components.wiim.api] Request to https://192.168.1.68:443/httpapi.asp?command=getPlayerStatusEx failed: Cannot connect to host 192.168.1.68:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1028)')]
2025-05-18 00:12:33.574 DEBUG (MainThread) [custom_components.wiim.api] WiiM HTTP GET https://192.168.1.68:443/httpapi.asp?command=getPlayerStatusEx (verify_ssl=False)
2025-05-18 00:12:33.576 DEBUG (MainThread) [custom_components.wiim.api] Request to https://192.168.1.68:443/httpapi.asp?command=getStatusEx failed: Cannot connect to host 192.168.1.68:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1028)')]
2025-05-18 00:12:33.576 DEBUG (MainThread) [custom_components.wiim.api] WiiM HTTP GET https://192.168.1.68:443/httpapi.asp?command=getStatusEx (verify_ssl=False)
2025-05-18 00:12:33.578 DEBUG (MainThread) [custom_components.wiim.api] Request to https://192.168.1.68:443/httpapi.asp?command=multiroom:getSlaveList failed: Cannot connect to host 192.168.1.68:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1028)')]
2025-05-18 00:12:33.579 DEBUG (MainThread) [custom_components.wiim.api] WiiM HTTP GET https://192.168.1.68:443/httpapi.asp?command=multiroom:getSlaveList (verify_ssl=False)
2025-05-18 00:12:33.582 DEBUG (MainThread) [custom_components.wiim.api] Request to https://192.168.1.116:443/httpapi.asp?command=getStatusEx failed: Cannot connect to host 192.168.1.116:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1028)')]
2025-05-18 00:12:33.583 DEBUG (MainThread) [custom_components.wiim.api] WiiM HTTP GET https://192.168.1.116:443/httpapi.asp?command=getStatusEx (verify_ssl=False)
2025-05-18 00:12:33.588 DEBUG (MainThread) [custom_components.wiim.api] Request to https://192.168.1.116:443/httpapi.asp?command=getPlayerStatusEx failed: Cannot connect to host 192.168.1.116:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1028)')]
2025-05-18 00:12:33.588 DEBUG (MainThread) [custom_components.wiim.api] WiiM HTTP GET https://192.168.1.116:443/httpapi.asp?command=getPlayerStatusEx (verify_ssl=False)
2025-05-18 00:12:33.590 DEBUG (MainThread) [custom_components.wiim.api] Request to https://192.168.1.116:443/httpapi.asp?command=multiroom:getSlaveList failed: Cannot connect to host 192.168.1.116:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1028)')]
2025-05-18 00:12:33.590 DEBUG (MainThread) [custom_components.wiim.api] WiiM HTTP GET https://192.168.1.116:443/httpapi.asp?command=multiroom:getSlaveList (verify_ssl=False)
2025-05-18 00:12:33.655 DEBUG (MainThread) [custom_components.wiim.api] https://192.168.1.68:443/httpapi.asp?command=getPlayerStatusEx -> 373 bytes JSON
2025-05-18 00:12:33.655 DEBUG (MainThread) [custom_components.wiim.api] Successful request on https://192.168.1.68:443/httpapi.asp?command=getPlayerStatusEx
2025-05-18 00:12:33.655 DEBUG (MainThread) [custom_components.wiim.api] Raw player status: {'type': '0', 'ch': '0', 'mode': '1', 'loop': '4', 'eq': '0', 'vendor': '', 'status': 'stop', 'curpos': '208000', 'offset_pts': '75760', 'totlen': '208000', 'Title': '47686F737473', 'Artist': '416E64726577204C6F636B696E67746F6E', 'Album': '4C616E646D616E202846726F6D2074686520506172616D6F756E742B204F726967696E616C2053657269657329', 'alarmflag': '0', 'plicount': '0', 'plicurr': '0', 'vol': '0', 'mute': '0'}
2025-05-18 00:12:33.655 DEBUG (MainThread) [custom_components.wiim.api] Parsed status: {'type': '0', 'ch': '0', 'mode': '1', 'loop_mode': '4', 'eq_preset': '0', 'vendor': '', 'play_status': 'stop', 'position_ms': '208000', 'offset_pts': '75760', 'duration_ms': '208000', 'title_hex': '47686F737473', 'artist_hex': '416E64726577204C6F636B696E67746F6E', 'album_hex': '4C616E646D616E202846726F6D2074686520506172616D6F756E742B204F726967696E616C2053657269657329', 'alarmflag': '0', 'plicount': '0', 'plicurr': '0', 'volume': 0, 'mute': False, 'title': 'Ghosts', 'artist': 'Andrew Lockington', 'album': 'Landman (From the Paramount+ Original Series)', 'power': True, 'volume_level': 0.0, 'position': 208, 'position_updated_at': 78213.148598418, 'duration': 208, 'play_mode': 'normal'}
2025-05-18 00:12:33.668 DEBUG (MainThread) [custom_components.wiim.api] https://192.168.1.116:443/httpapi.asp?command=getPlayerStatusEx -> 267 bytes JSON
2025-05-18 00:12:33.668 DEBUG (MainThread) [custom_components.wiim.api] Successful request on https://192.168.1.116:443/httpapi.asp?command=getPlayerStatusEx
2025-05-18 00:12:33.669 DEBUG (MainThread) [custom_components.wiim.api] Raw player status: {'type': '0', 'ch': '0', 'mode': '-1', 'loop': '4', 'eq': '0', 'vendor': '', 'status': 'none', 'curpos': '0', 'offset_pts': '0', 'totlen': '0', 'Title': '556E6B6E6F776E', 'Artist': '556E6B6E6F776E', 'Album': '556E6B6E6F776E', 'alarmflag': '0', 'plicount': '0', 'plicurr': '0', 'vol': '18', 'mute': '0'}
2025-05-18 00:12:33.669 DEBUG (MainThread) [custom_components.wiim.api] Parsed status: {'type': '0', 'ch': '0', 'mode': '-1', 'loop_mode': '4', 'eq_preset': '0', 'vendor': '', 'play_status': 'none', 'position_ms': '0', 'offset_pts': '0', 'duration_ms': '0', 'title_hex': '556E6B6E6F776E', 'artist_hex': '556E6B6E6F776E', 'album_hex': '556E6B6E6F776E', 'alarmflag': '0', 'plicount': '0', 'plicurr': '0', 'volume': 18, 'mute': False, 'title': 'Unknown', 'artist': 'Unknown', 'album': 'Unknown', 'power': True, 'volume_level': 0.18, 'position': 0, 'position_updated_at': 78213.161691041, 'duration': 0, 'play_mode': 'normal'}
2025-05-18 00:12:33.712 DEBUG (MainThread) [custom_components.wiim.api] https://192.168.1.68:443/httpapi.asp?command=getStatusEx -> 2724 bytes JSON
2025-05-18 00:12:33.712 DEBUG (MainThread) [custom_components.wiim.api] Successful request on https://192.168.1.68:443/httpapi.asp?command=getStatusEx
2025-05-18 00:12:33.713 DEBUG (MainThread) [custom_components.wiim.api] https://192.168.1.68:443/httpapi.asp?command=multiroom:getSlaveList -> 53 bytes JSON
2025-05-18 00:12:33.713 DEBUG (MainThread) [custom_components.wiim.api] Successful request on https://192.168.1.68:443/httpapi.asp?command=multiroom:getSlaveList
2025-05-18 00:12:33.714 DEBUG (MainThread) [custom_components.wiim.api] WiiM HTTP GET https://192.168.1.68:443/httpapi.asp?command=getPlayerCmd:switchmode (verify_ssl=False)
2025-05-18 00:12:33.722 DEBUG (MainThread) [custom_components.wiim.api] https://192.168.1.116:443/httpapi.asp?command=getStatusEx -> 2715 bytes JSON
2025-05-18 00:12:33.722 DEBUG (MainThread) [custom_components.wiim.api] Successful request on https://192.168.1.116:443/httpapi.asp?command=getStatusEx
2025-05-18 00:12:33.723 DEBUG (MainThread) [custom_components.wiim.api] https://192.168.1.116:443/httpapi.asp?command=multiroom:getSlaveList -> 53 bytes JSON
2025-05-18 00:12:33.724 DEBUG (MainThread) [custom_components.wiim.api] Successful request on https://192.168.1.116:443/httpapi.asp?command=multiroom:getSlaveList
2025-05-18 00:12:33.725 DEBUG (MainThread) [custom_components.wiim.api] WiiM HTTP GET https://192.168.1.116:443/httpapi.asp?command=getPlayerCmd:switchmode (verify_ssl=False)
2025-05-18 00:12:33.795 DEBUG (MainThread) [custom_components.wiim.api] https://192.168.1.68:443/httpapi.asp?command=getPlayerCmd:switchmode -> non-JSON: unknown command
2025-05-18 00:12:33.796 DEBUG (MainThread) [custom_components.wiim.api] Successful request on https://192.168.1.68:443/httpapi.asp?command=getPlayerCmd:switchmode
2025-05-18 00:12:33.796 DEBUG (MainThread) [custom_components.wiim.coordinator] Finished fetching wiim_192.168.1.68 data in 0.351 seconds (success: True)
2025-05-18 00:12:33.800 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('custom_components.wiim.media_player',) inside the event loop by custom integration 'wiim' at custom_components/wiim/__init__.py, line 28: await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS) (offender: /ha-venv/lib/python3.13/site-packages/homeassistant/loader.py, line 1282: return importlib.import_module(f"{self.pkg_path}.{platform_name}")), please report it to the author of the 'wiim' custom integration
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module
Traceback (most recent call last):
  File "/ha-venv/bin/hass", line 8, in <module>
    sys.exit(main())
  File "/ha-venv/lib/python3.13/site-packages/homeassistant/__main__.py", line 213, in main
    exit_code = runner.run(runtime_conf)
  File "/ha-venv/lib/python3.13/site-packages/homeassistant/runner.py", line 154, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 706, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 677, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2026, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/ha-venv/lib/python3.13/site-packages/homeassistant/config_entries.py", line 894, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/ha-venv/lib/python3.13/site-packages/homeassistant/config_entries.py", line 660, in async_setup
    await self.__async_setup_with_context(hass, integration)
  File "/ha-venv/lib/python3.13/site-packages/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
  File "/workspaces/ha-wiim/config/custom_components/wiim/__init__.py", line 28, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)

2025-05-18 00:12:33.801 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry WiiM 192.168.1.68 for wiim
Traceback (most recent call last):
  File "/ha-venv/lib/python3.13/site-packages/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ha-wiim/config/custom_components/wiim/__init__.py", line 28, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
  File "/ha-venv/lib/python3.13/site-packages/homeassistant/config_entries.py", line 2568, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/ha-venv/lib/python3.13/site-packages/homeassistant/loader.py", line 1163, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/ha-venv/lib/python3.13/site-packages/homeassistant/loader.py", line 1163, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/ha-venv/lib/python3.13/site-packages/homeassistant/loader.py", line 1163, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  [Previous line repeated 1 more time]
  File "/ha-venv/lib/python3.13/site-packages/homeassistant/loader.py", line 1151, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/ha-venv/lib/python3.13/site-packages/homeassistant/loader.py", line 1076, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/ha-venv/lib/python3.13/site-packages/homeassistant/loader.py", line 1250, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/ha-venv/lib/python3.13/site-packages/homeassistant/loader.py", line 1282, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ha-venv/lib/python3.13/site-packages/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/workspaces/ha-wiim/config/custom_components/wiim/media_player.py", line 20, in <module>
    from homeassistant.components.media_player.const import (
    ...<2 lines>...
    )
ImportError: cannot import name 'ATTR_GROUP_LEADER' from 'homeassistant.components.media_player.const' (/ha-venv/lib/python3.13/site-packages/homeassistant/components/media_player/const.py)
2025-05-18 00:12:33.807 DEBUG (MainThread) [custom_components.wiim.api] https://192.168.1.116:443/httpapi.asp?command=getPlayerCmd:switchmode -> non-JSON: unknown command
2025-05-18 00:12:33.807 DEBUG (MainThread) [custom_components.wiim.api] Successful request on https://192.168.1.116:443/httpapi.asp?command=getPlayerCmd:switchmode
2025-05-18 00:12:33.807 DEBUG (MainThread) [custom_components.wiim.coordinator] Finished fetching wiim_192.168.1.116 data in 0.362 seconds (success: True)
2025-05-18 00:12:33.817 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry WiiM 192.168.1.116 for wiim
Traceback (most recent call last):
  File "/ha-venv/lib/python3.13/site-packages/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ha-wiim/config/custom_components/wiim/__init__.py", line 28, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
  File "/ha-venv/lib/python3.13/site-packages/homeassistant/config_entries.py", line 2568, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/ha-venv/lib/python3.13/site-packages/homeassistant/loader.py", line 1163, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/ha-venv/lib/python3.13/site-packages/homeassistant/loader.py", line 1163, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/ha-venv/lib/python3.13/site-packages/homeassistant/loader.py", line 1163, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  [Previous line repeated 1 more time]
  File "/ha-venv/lib/python3.13/site-packages/homeassistant/loader.py", line 1151, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/ha-venv/lib/python3.13/site-packages/homeassistant/loader.py", line 1076, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/ha-venv/lib/python3.13/site-packages/homeassistant/loader.py", line 1250, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/ha-venv/lib/python3.13/site-packages/homeassistant/loader.py", line 1282, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ha-venv/lib/python3.13/site-packages/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/workspaces/ha-wiim/config/custom_components/wiim/media_player.py", line 20, in <module>
    from homeassistant.components.media_player.const import (
    ...<2 lines>...
    )
ImportError: cannot import name 'ATTR_GROUP_LEADER' from 'homeassistant.components.media_player.const' (/ha-venv/lib/python3.13/site-packages/homeassistant/components/media_player/const.py)
2025-05-18 00:12:33.971 DEBUG (MainThread) [homeassistant.components.ssdp.server] Binding UPnP HTTP server to: 172.24.9.234:40000
2025-05-18 00:12:33.973 DEBUG (MainThread) [homeassistant.components.ssdp.server] Binding UPnP HTTP server to: fe80::215:5dff:fe55:3485%2:40000
2025-05-18 00:12:34.197 WARNING (MainThread) [asyncio] Executing <Task pending name='Task-85' coro=<UpnpServer.async_start() running at /ha-venv/lib/python3.13/site-packages/async_upnp_client/server.py:1353> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.13/asyncio/base_events.py:459> cb=[gather.<locals>._done_callback() at /usr/local/lib/python3.13/asyncio/tasks.py:820] created at /usr/local/lib/python3.13/asyncio/tasks.py:748> took 0.131 seconds
2025-05-18 00:12:34.234 DEBUG (MainThread) [homeassistant.components.ssdp.scanner] SSDP: ssdp_device: <SsdpDevice(UUID:4B66B98B-8941-40C0-844C-9075140BF8D9)>, dst: upnp:rootdevice, source: SsdpSource.ADVERTISEMENT_ALIVE
2025-05-18 00:12:34.325 ERROR (SyncWorker_0) [aiodhcpwatcher] Cannot watch for dhcp packets without a functional packet filter: libpcap is not available. Cannot compile filter !
2025-05-18 00:13:01.226 DEBUG (MainThread) [homeassistant.components.ssdp.scanner] SSDP: ssdp_device: <SsdpDevice(UUID:4B66B98B-8941-40C0-844C-9075140BF8D9)>, dst: UUID:4B66B98B-8941-40C0-844C-9075140BF8D9, source: SsdpSource.ADVERTISEMENT_ALIVE
2025-05-18 00:13:28.730 DEBUG (MainThread) [homeassistant.components.ssdp.scanner] SSDP: ssdp_device: <SsdpDevice(UUID:4B66B98B-8941-40C0-844C-9075140BF8D9)>, dst: urn:home-assistant.io:device:HomeAssistant:1, source: SsdpSource.ADVERTISEMENT_ALIVE
2025-05-18 00:20:56.692 ERROR (MainThread) [root] Uncaught exception
Traceback (most recent call last):
  File "/ha-venv/bin/hass", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/ha-venv/lib/python3.13/site-packages/homeassistant/__main__.py", line 213, in main
    exit_code = runner.run(runtime_conf)
  File "/ha-venv/lib/python3.13/site-packages/homeassistant/runner.py", line 154, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 706, in run_until_complete
    self.run_forever()
    ~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 677, in run_forever
    self._run_once()
    ~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 1996, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/local/lib/python3.13/selectors.py", line 452, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
